#---------------------------------------------#
#       build/environment configuration       #
#---------------------------------------------#

version: '{build}'

build:
  project: Exprelsior.sln
  verbosity: minimal

image: Visual Studio 2019
configuration: Release
platform: Any CPU

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
  
environment:
  certificate_pass:
    secure: 4HtCHAFuggxhqnism3hA/sk1r3paygf0KLvQwzy1S+0=
  certificate_container_name:
    secure: CEDPYyDEmpw2yxtLGjryfesP1SSi8LtCDKf6FN6sDC4=

#-------------------------------------#
#       pre-build configuration       #
#-------------------------------------#

before_build:

  # Extract version, release notes, pre-release flag.
  - ps: |
        $props = ([xml](Get-Content "Directory.Build.props")).Project.PropertyGroup
        $vPrefix = $props.VersionPrefix
        $vSuffix = $props.VersionSuffix
        $releaseNotes = if ($props.PackageReleaseNotes.GetType() -eq [System.Xml.XmlElement]) { $props.PackageReleaseNotes.InnerText } else { $props.PackageReleaseNotes }
        
        $env:fullVersion = @{ $true = "$($vPrefix)-$($vSuffix)"; $false = $($vPrefix) }[-not ([string]::IsNullOrEmpty($vSuffix))]
        $env:isPreRelease = @{ $true = "true"; $false = "false" }[-not ([string]::IsNullOrEmpty($vSuffix))]
        $env:releaseNotes = @{ $true = $releaseNotes.Replace("`n", '\n').TrimEnd().Trim('\n'); $false = "$env:fullVersion release!" }[-not ([string]::IsNullOrEmpty($releaseNotes))]
        
        Update-AppveyorBuild -Version "$env:fullVersion Build-$env:APPVEYOR_BUILD_VERSION"
  
  - ps: dotnet restore

#-----------------------------------------#
#       build trigger configuration       #
#-----------------------------------------#

skip_commits:
  files:
    - '**/*.md'
    - 'license'

skip_tags: false

#-----------------------------------#
#       publish configuration       #
#-----------------------------------#

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Exprelsior/bin/$(configuration)/Binaries
    name: Exprelsior.$(fullVersion)
    type: zip

  - path: Exprelsior/bin/$(configuration)/Package/*.nupkg

  - path: Exprelsior.Shared/bin/$(configuration)/Package/*.nupkg

#---------------------------------#
#      deploy configuration       #
#---------------------------------#

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(releaseNotes)
    draft: false
    prerelease: $(isPreRelease)
    auth_token:
      secure: 17uIp5Xz3DUfAUcfU6n/DajZ45rm5HVKrhTYVYJ4Z8XocWZvtSzhfZTfak6P6emy
    on:
      APPVEYOR_REPO_TAG: true

  - provider: NuGet
    api_key:
      secure: pF8W2j/TXfR8dLUpvBIabRDxkz0ye8u+cCQrsWOczf5C6QiyRKWY8M6dvbW1fAcK
    on:
      APPVEYOR_REPO_TAG: true
