#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

branches:
  only:
    - master
    - dev

skip_tags: false

skip_commits:
  files:
    - '**/*.md'
    - 'license'

max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2019

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  project: Exprelsior.sln
  verbosity: minimal

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#          build scripts          #
#---------------------------------#

before_build:
  - ps: |
        $props = [xml](Get-Content "Directory.Build.props")
        $prefix = $props.Project.PropertyGroup.VersionPrefix
        $suffix = $props.Project.PropertyGroup.VersionSuffix
        $full = @{ $true = "$($prefix)-$($suffix)"; $false = $($prefix) }[-not ([string]::IsNullOrEmpty($suffix))]
        Update-AppveyorBuild -Version "$full Build-$env:APPVEYOR_BUILD_VERSION"
        
        $isPreRelease = @{ $true = "true"; $false = "false" }[-not ([string]::IsNullOrEmpty($suffix))]
        Set-AppveyorBuildVariable 'pre_release' $isPreRelease
        
        $releaseNotes = $props.Project.PropertyGroup.PackageReleaseNotes
        Set-AppveyorBuildVariable 'release_notes' $releaseNotes
        
        dotnet restore

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Exprelsior/bin/$(configuration)
    name: Exprelsior
    type: zip

  - path: '**\*.nupkg'

  #---------------------------------#
  #      deploy configuration       #
  #---------------------------------#

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(release_notes)
    draft: false
    prerelease: $(pre_release)
    auth_token:
      secure: 17uIp5Xz3DUfAUcfU6n/DajZ45rm5HVKrhTYVYJ4Z8XocWZvtSzhfZTfak6P6emy
    on:
      branch: master
      APPVEYOR_REPO_TAG: true

  - provider: NuGet
    api_key:
      secure: pF8W2j/TXfR8dLUpvBIabRDxkz0ye8u+cCQrsWOczf5C6QiyRKWY8M6dvbW1fAcK
    on:
      branch: master
      APPVEYOR_REPO_TAG: true